### ISSUE TITLE
Problem in apps/apps/oauth2/authorize(request)

### ISSUE THREAD

**Issue by kwmartin** [jockerz/StarletteStarter#1]
```
> /usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py(128)execute()
-> self.await_(_cursor.execute(operation, parameters))
(Pdb) 
INFO:     Waiting for connections to close. (CTRL+C to force quit)
sqlite3.IntegrityError: UNIQUE constraint failed: account_user.email
> /usr/local/lib/python3.10/site-packages/aiosqlite/core.py(115)run()
-> result = function()
(Pdb) 
```
for
```
(Pdb) operation
'INSERT INTO account_user (username, password, email, name, avatar, is_staff, is_admin, is_active, update_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'
(Pdb) parameters
('martin_g', '$pbkdf2-sha256$29000$qBVCKMVYCyEkRGjN.V/LOQ$doYwuvxITOhbBSh1dmLjBxT2xrzg5w5FoDMEsAMyzXk', 'martin@granitesemi.com', 'Ken Martin', None, 0, 0, 1, None)
(Pdb) 
```
I checked the data base using the command line, and the email is already present, and has the same value that is being written into it. In apps/apps/account/models.py for the class:
```
class User(Base, UserMixin):
    __tablename__ = f'{TABLE_PREFIX}_user'

```
on line 25 we have:
```
    email: Mapped[str] = mapped_column(EmailType, unique=True)
```
which can account for the exception, but still re-writing the same value should not trigger a non-unique error so maybe sqllite has a bug as well? If I remember correctly (a while ago), I don't think this would have triggered an error in postgresql?
My guess is all the information from the google account is being stored into the User table (just a guess), but half way up the backtrace (see below): we have:
```
-> rec.execute(self)
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py(642)execute()
```
which is in function:
```
class SaveUpdateAll(PostSortRec):
    __slots__ = ("mapper", "sort_key")

    def __init__(self, uow, mapper):
        self.mapper = mapper
        self.sort_key = ("SaveUpdateAll", mapper._sort_key)
        assert mapper is mapper.base_mapper
```
It's difficult to think what to change as with so much interaction and complication, any changes might break something else. Also, for my purposes, I really want to use mongoDb (even though I'm a newbie in mongo, I just like it better; in postgreSql, nowadays, everything is done using Jsonb anyways. The backtrace follows for anyone that is experience in this area (I'm not).

```
(Pdb) bt
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py(1972)commit()
-> trans.commit(_to_root=True)
  <string>(2)commit()
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py(139)_go()
-> ret_value = fn(self, *arg, **kw)
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py(1257)commit()
-> self._prepare_impl()
  <string>(2)_prepare_impl()
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py(139)_go()
-> ret_value = fn(self, *arg, **kw)
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py(1232)_prepare_impl()
-> self.session.flush()
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py(4296)flush()
-> self._flush(objects)
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py(4392)_flush()
-> flush_context.execute()
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py(466)execute()
-> rec.execute(self)
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py(642)execute()
-> util.preloaded.orm_persistence.save_obj(
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py(93)save_obj()
-> _emit_insert_statements(
  /usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py(1233)_emit_insert_statements()
-> result = connection.execute(
  /usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py(1408)execute()
-> return meth(
  /usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py(513)_execute_on_connection()
-> return connection._execute_clauseelement(
  /usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py(1630)_execute_clauseelement()
-> ret = self._execute_context(
  /usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py(1839)_execute_context()
-> return self._exec_single_context(
  /usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py(1960)_exec_single_context()
-> self.dialect.do_execute(
  /usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py(924)do_execute()
-> cursor.execute(statement, parameters)
> /usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py(123)execute()
-> _cursor = self.await_(self._connection.cursor())
(Pdb) 
```

**Comment by kwmartin** [comment]
Problem is due to defining an admin user in .env with the same email as the user obtained from google. I haven't figured out a workable solution yet.

I have an additional problem related to SqlAlchemy complexity where in Session (I believe db is a Session()?) an AnonymousUser is created and returned by OAuth2AccountCRUD.create that contains _sa_instance_state = <sqlalchemy.orm.state.InstanceState object at 0x7f282dd51cc0>. I have plenty of experience with postgreSql but practically none with SqlAlchemy.ORM. It's like having to learn a brand new complicated language with not great documentation (at least with respect to creating an AnonymousUser (somewhere unknown), and I guess I have to inspect db to figure out why _sa_instance_state is added. It looks like I need to figure out how the state machine in SqlAlchemy.ORM works? The backtrace has 21 frames to work through. I don't know why SqlAlchemy is necessary as it sure complicates debugging when it breaks? For user authorization and authentication, it doesn't happen often so it won't load a site down, and a simple database approach is called for (assuming it has @csrf_protect)?

**Comment by jockerz** [comment]
Hi @kwmartin 
Thank you for pointing out the issue.
I am working on it

**Comment by jockerz** [comment]
> Problem is due to defining an admin user in .env with the same email as the user obtained from google. I haven't figured out a workable solution yet.

Providing the email on the `.env` as `ADMIN ` will get the email registered on the application start up.
To link your 3rd party OAuth provider, you need to login first.
Then go to *Settings > Linked Account*
Then link you 3rd party Oauth proveider from there.

Though, the issue (`sqlite3.IntegrityError` exception) indeed need to be fixed.
